version: '3'

services:
  laravel:
    build: ./laravel
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: example

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - laravel
    networks:
      - app-network

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: laravel

  random_http:
    image: <your-random-http-image>
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
